FROM tomcat:7-jre7

MAINTAINER limin mli@yihecloud.com

WORKDIR /program

COPY target/HackerTopic2-0.0.1-SNAPSHOT.jar /program/HackerTopic2.jar

#CMD ["java","-jar","/program/HackerTopic2.jar"]
